export interface CityEntry {
  city: string
  country: string
  timezone: string
}

// Comprehensive world cities database — maps city names to IANA timezones
// Organized by region for maintainability
export const WORLD_CITIES: CityEntry[] = [
  // ── Africa ──────────────────────────────────────────
  { city: 'Abidjan', country: 'Ivory Coast', timezone: 'Africa/Abidjan' },
  { city: 'Accra', country: 'Ghana', timezone: 'Africa/Accra' },
  { city: 'Addis Ababa', country: 'Ethiopia', timezone: 'Africa/Addis_Ababa' },
  { city: 'Algiers', country: 'Algeria', timezone: 'Africa/Algiers' },
  { city: 'Oran', country: 'Algeria', timezone: 'Africa/Algiers' },
  { city: 'Constantine', country: 'Algeria', timezone: 'Africa/Algiers' },
  { city: 'Antananarivo', country: 'Madagascar', timezone: 'Indian/Antananarivo' },
  { city: 'Bamako', country: 'Mali', timezone: 'Africa/Bamako' },
  { city: 'Brazzaville', country: 'Congo', timezone: 'Africa/Brazzaville' },
  { city: 'Cairo', country: 'Egypt', timezone: 'Africa/Cairo' },
  { city: 'Alexandria', country: 'Egypt', timezone: 'Africa/Cairo' },
  { city: 'Giza', country: 'Egypt', timezone: 'Africa/Cairo' },
  { city: 'Cape Town', country: 'South Africa', timezone: 'Africa/Johannesburg' },
  { city: 'Johannesburg', country: 'South Africa', timezone: 'Africa/Johannesburg' },
  { city: 'Pretoria', country: 'South Africa', timezone: 'Africa/Johannesburg' },
  { city: 'Durban', country: 'South Africa', timezone: 'Africa/Johannesburg' },
  { city: 'Casablanca', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Rabat', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Marrakech', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Fes', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Tangier', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Agadir', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Meknes', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Oujda', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Kenitra', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Tetouan', country: 'Morocco', timezone: 'Africa/Casablanca' },
  { city: 'Dakar', country: 'Senegal', timezone: 'Africa/Dakar' },
  { city: 'Dar es Salaam', country: 'Tanzania', timezone: 'Africa/Dar_es_Salaam' },
  { city: 'Douala', country: 'Cameroon', timezone: 'Africa/Douala' },
  { city: 'Yaoundé', country: 'Cameroon', timezone: 'Africa/Douala' },
  { city: 'Harare', country: 'Zimbabwe', timezone: 'Africa/Harare' },
  { city: 'Kampala', country: 'Uganda', timezone: 'Africa/Kampala' },
  { city: 'Khartoum', country: 'Sudan', timezone: 'Africa/Khartoum' },
  { city: 'Kinshasa', country: 'DR Congo', timezone: 'Africa/Kinshasa' },
  { city: 'Lagos', country: 'Nigeria', timezone: 'Africa/Lagos' },
  { city: 'Abuja', country: 'Nigeria', timezone: 'Africa/Lagos' },
  { city: 'Kano', country: 'Nigeria', timezone: 'Africa/Lagos' },
  { city: 'Ibadan', country: 'Nigeria', timezone: 'Africa/Lagos' },
  { city: 'Luanda', country: 'Angola', timezone: 'Africa/Luanda' },
  { city: 'Lusaka', country: 'Zambia', timezone: 'Africa/Lusaka' },
  { city: 'Maputo', country: 'Mozambique', timezone: 'Africa/Maputo' },
  { city: 'Mogadishu', country: 'Somalia', timezone: 'Africa/Mogadishu' },
  { city: 'Nairobi', country: 'Kenya', timezone: 'Africa/Nairobi' },
  { city: 'Mombasa', country: 'Kenya', timezone: 'Africa/Nairobi' },
  { city: 'Tunis', country: 'Tunisia', timezone: 'Africa/Tunis' },
  { city: 'Tripoli', country: 'Libya', timezone: 'Africa/Tripoli' },
  { city: 'Windhoek', country: 'Namibia', timezone: 'Africa/Windhoek' },
  { city: 'Kigali', country: 'Rwanda', timezone: 'Africa/Kigali' },

  // ── Europe ──────────────────────────────────────────
  { city: 'Amsterdam', country: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { city: 'Rotterdam', country: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { city: 'The Hague', country: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { city: 'Athens', country: 'Greece', timezone: 'Europe/Athens' },
  { city: 'Thessaloniki', country: 'Greece', timezone: 'Europe/Athens' },
  { city: 'Barcelona', country: 'Spain', timezone: 'Europe/Madrid' },
  { city: 'Madrid', country: 'Spain', timezone: 'Europe/Madrid' },
  { city: 'Seville', country: 'Spain', timezone: 'Europe/Madrid' },
  { city: 'Valencia', country: 'Spain', timezone: 'Europe/Madrid' },
  { city: 'Málaga', country: 'Spain', timezone: 'Europe/Madrid' },
  { city: 'Bilbao', country: 'Spain', timezone: 'Europe/Madrid' },
  { city: 'Belgrade', country: 'Serbia', timezone: 'Europe/Belgrade' },
  { city: 'Berlin', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Munich', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Hamburg', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Frankfurt', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Cologne', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Stuttgart', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Düsseldorf', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Dortmund', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Leipzig', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Dresden', country: 'Germany', timezone: 'Europe/Berlin' },
  { city: 'Bratislava', country: 'Slovakia', timezone: 'Europe/Bratislava' },
  { city: 'Brussels', country: 'Belgium', timezone: 'Europe/Brussels' },
  { city: 'Antwerp', country: 'Belgium', timezone: 'Europe/Brussels' },
  { city: 'Bucharest', country: 'Romania', timezone: 'Europe/Bucharest' },
  { city: 'Budapest', country: 'Hungary', timezone: 'Europe/Budapest' },
  { city: 'Copenhagen', country: 'Denmark', timezone: 'Europe/Copenhagen' },
  { city: 'Dublin', country: 'Ireland', timezone: 'Europe/Dublin' },
  { city: 'Cork', country: 'Ireland', timezone: 'Europe/Dublin' },
  { city: 'Helsinki', country: 'Finland', timezone: 'Europe/Helsinki' },
  { city: 'Istanbul', country: 'Turkey', timezone: 'Europe/Istanbul' },
  { city: 'Ankara', country: 'Turkey', timezone: 'Europe/Istanbul' },
  { city: 'Izmir', country: 'Turkey', timezone: 'Europe/Istanbul' },
  { city: 'Antalya', country: 'Turkey', timezone: 'Europe/Istanbul' },
  { city: 'Bursa', country: 'Turkey', timezone: 'Europe/Istanbul' },
  { city: 'Kyiv', country: 'Ukraine', timezone: 'Europe/Kyiv' },
  { city: 'Kharkiv', country: 'Ukraine', timezone: 'Europe/Kyiv' },
  { city: 'Odesa', country: 'Ukraine', timezone: 'Europe/Kyiv' },
  { city: 'Lisbon', country: 'Portugal', timezone: 'Europe/Lisbon' },
  { city: 'Porto', country: 'Portugal', timezone: 'Europe/Lisbon' },
  { city: 'London', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Manchester', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Birmingham', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Glasgow', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Liverpool', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Edinburgh', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Bristol', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Leeds', country: 'United Kingdom', timezone: 'Europe/London' },
  { city: 'Luxembourg', country: 'Luxembourg', timezone: 'Europe/Luxembourg' },
  { city: 'Milan', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Rome', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Naples', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Turin', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Florence', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Venice', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Bologna', country: 'Italy', timezone: 'Europe/Rome' },
  { city: 'Minsk', country: 'Belarus', timezone: 'Europe/Minsk' },
  { city: 'Moscow', country: 'Russia', timezone: 'Europe/Moscow' },
  { city: 'Saint Petersburg', country: 'Russia', timezone: 'Europe/Moscow' },
  { city: 'Nizhny Novgorod', country: 'Russia', timezone: 'Europe/Moscow' },
  { city: 'Kazan', country: 'Russia', timezone: 'Europe/Moscow' },
  { city: 'Oslo', country: 'Norway', timezone: 'Europe/Oslo' },
  { city: 'Bergen', country: 'Norway', timezone: 'Europe/Oslo' },
  { city: 'Paris', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Marseille', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Lyon', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Toulouse', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Nice', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Bordeaux', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Lille', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Strasbourg', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Nantes', country: 'France', timezone: 'Europe/Paris' },
  { city: 'Prague', country: 'Czech Republic', timezone: 'Europe/Prague' },
  { city: 'Brno', country: 'Czech Republic', timezone: 'Europe/Prague' },
  { city: 'Riga', country: 'Latvia', timezone: 'Europe/Riga' },
  { city: 'Sofia', country: 'Bulgaria', timezone: 'Europe/Sofia' },
  { city: 'Stockholm', country: 'Sweden', timezone: 'Europe/Stockholm' },
  { city: 'Gothenburg', country: 'Sweden', timezone: 'Europe/Stockholm' },
  { city: 'Tallinn', country: 'Estonia', timezone: 'Europe/Tallinn' },
  { city: 'Vienna', country: 'Austria', timezone: 'Europe/Vienna' },
  { city: 'Salzburg', country: 'Austria', timezone: 'Europe/Vienna' },
  { city: 'Graz', country: 'Austria', timezone: 'Europe/Vienna' },
  { city: 'Vilnius', country: 'Lithuania', timezone: 'Europe/Vilnius' },
  { city: 'Warsaw', country: 'Poland', timezone: 'Europe/Warsaw' },
  { city: 'Kraków', country: 'Poland', timezone: 'Europe/Warsaw' },
  { city: 'Wrocław', country: 'Poland', timezone: 'Europe/Warsaw' },
  { city: 'Gdańsk', country: 'Poland', timezone: 'Europe/Warsaw' },
  { city: 'Zagreb', country: 'Croatia', timezone: 'Europe/Zagreb' },
  { city: 'Zurich', country: 'Switzerland', timezone: 'Europe/Zurich' },
  { city: 'Geneva', country: 'Switzerland', timezone: 'Europe/Zurich' },
  { city: 'Bern', country: 'Switzerland', timezone: 'Europe/Zurich' },
  { city: 'Basel', country: 'Switzerland', timezone: 'Europe/Zurich' },
  { city: 'Reykjavik', country: 'Iceland', timezone: 'Atlantic/Reykjavik' },

  // ── Asia ────────────────────────────────────────────
  { city: 'Almaty', country: 'Kazakhstan', timezone: 'Asia/Almaty' },
  { city: 'Amman', country: 'Jordan', timezone: 'Asia/Amman' },
  { city: 'Baghdad', country: 'Iraq', timezone: 'Asia/Baghdad' },
  { city: 'Baku', country: 'Azerbaijan', timezone: 'Asia/Baku' },
  { city: 'Bangkok', country: 'Thailand', timezone: 'Asia/Bangkok' },
  { city: 'Chiang Mai', country: 'Thailand', timezone: 'Asia/Bangkok' },
  { city: 'Phuket', country: 'Thailand', timezone: 'Asia/Bangkok' },
  { city: 'Beijing', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Shanghai', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Guangzhou', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Shenzhen', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Chengdu', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Hangzhou', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Wuhan', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Nanjing', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Xi\'an', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Tianjin', country: 'China', timezone: 'Asia/Shanghai' },
  { city: 'Beirut', country: 'Lebanon', timezone: 'Asia/Beirut' },
  { city: 'Colombo', country: 'Sri Lanka', timezone: 'Asia/Colombo' },
  { city: 'Dhaka', country: 'Bangladesh', timezone: 'Asia/Dhaka' },
  { city: 'Dubai', country: 'UAE', timezone: 'Asia/Dubai' },
  { city: 'Abu Dhabi', country: 'UAE', timezone: 'Asia/Dubai' },
  { city: 'Sharjah', country: 'UAE', timezone: 'Asia/Dubai' },
  { city: 'Doha', country: 'Qatar', timezone: 'Asia/Qatar' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
  { city: 'Hanoi', country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
  { city: 'Da Nang', country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
  { city: 'Hong Kong', country: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
  { city: 'Jakarta', country: 'Indonesia', timezone: 'Asia/Jakarta' },
  { city: 'Bandung', country: 'Indonesia', timezone: 'Asia/Jakarta' },
  { city: 'Surabaya', country: 'Indonesia', timezone: 'Asia/Jakarta' },
  { city: 'Bali', country: 'Indonesia', timezone: 'Asia/Makassar' },
  { city: 'Jerusalem', country: 'Israel', timezone: 'Asia/Jerusalem' },
  { city: 'Tel Aviv', country: 'Israel', timezone: 'Asia/Jerusalem' },
  { city: 'Haifa', country: 'Israel', timezone: 'Asia/Jerusalem' },
  { city: 'Kabul', country: 'Afghanistan', timezone: 'Asia/Kabul' },
  { city: 'Karachi', country: 'Pakistan', timezone: 'Asia/Karachi' },
  { city: 'Lahore', country: 'Pakistan', timezone: 'Asia/Karachi' },
  { city: 'Islamabad', country: 'Pakistan', timezone: 'Asia/Karachi' },
  { city: 'Kathmandu', country: 'Nepal', timezone: 'Asia/Kathmandu' },
  { city: 'Kolkata', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Mumbai', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'New Delhi', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Delhi', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Bangalore', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Hyderabad', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Chennai', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Pune', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Ahmedabad', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Jaipur', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Lucknow', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Surat', country: 'India', timezone: 'Asia/Kolkata' },
  { city: 'Kuala Lumpur', country: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
  { city: 'Penang', country: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
  { city: 'Kuwait City', country: 'Kuwait', timezone: 'Asia/Kuwait' },
  { city: 'Manila', country: 'Philippines', timezone: 'Asia/Manila' },
  { city: 'Cebu', country: 'Philippines', timezone: 'Asia/Manila' },
  { city: 'Davao', country: 'Philippines', timezone: 'Asia/Manila' },
  { city: 'Muscat', country: 'Oman', timezone: 'Asia/Muscat' },
  { city: 'Phnom Penh', country: 'Cambodia', timezone: 'Asia/Phnom_Penh' },
  { city: 'Siem Reap', country: 'Cambodia', timezone: 'Asia/Phnom_Penh' },
  { city: 'Riyadh', country: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { city: 'Jeddah', country: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { city: 'Mecca', country: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { city: 'Medina', country: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { city: 'Seoul', country: 'South Korea', timezone: 'Asia/Seoul' },
  { city: 'Busan', country: 'South Korea', timezone: 'Asia/Seoul' },
  { city: 'Singapore', country: 'Singapore', timezone: 'Asia/Singapore' },
  { city: 'Taipei', country: 'Taiwan', timezone: 'Asia/Taipei' },
  { city: 'Tashkent', country: 'Uzbekistan', timezone: 'Asia/Tashkent' },
  { city: 'Tbilisi', country: 'Georgia', timezone: 'Asia/Tbilisi' },
  { city: 'Tehran', country: 'Iran', timezone: 'Asia/Tehran' },
  { city: 'Tokyo', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Osaka', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Kyoto', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Yokohama', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Nagoya', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Sapporo', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Fukuoka', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Kobe', country: 'Japan', timezone: 'Asia/Tokyo' },
  { city: 'Ulaanbaatar', country: 'Mongolia', timezone: 'Asia/Ulaanbaatar' },
  { city: 'Yangon', country: 'Myanmar', timezone: 'Asia/Yangon' },
  { city: 'Yerevan', country: 'Armenia', timezone: 'Asia/Yerevan' },

  // ── North America ───────────────────────────────────
  { city: 'Anchorage', country: 'USA', timezone: 'America/Anchorage' },
  { city: 'Atlanta', country: 'USA', timezone: 'America/New_York' },
  { city: 'Austin', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Baltimore', country: 'USA', timezone: 'America/New_York' },
  { city: 'Boston', country: 'USA', timezone: 'America/New_York' },
  { city: 'Charlotte', country: 'USA', timezone: 'America/New_York' },
  { city: 'Chicago', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Cleveland', country: 'USA', timezone: 'America/New_York' },
  { city: 'Columbus', country: 'USA', timezone: 'America/New_York' },
  { city: 'Dallas', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Denver', country: 'USA', timezone: 'America/Denver' },
  { city: 'Detroit', country: 'USA', timezone: 'America/Detroit' },
  { city: 'Honolulu', country: 'USA', timezone: 'Pacific/Honolulu' },
  { city: 'Houston', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Indianapolis', country: 'USA', timezone: 'America/Indiana/Indianapolis' },
  { city: 'Jacksonville', country: 'USA', timezone: 'America/New_York' },
  { city: 'Kansas City', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Las Vegas', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'Los Angeles', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'Memphis', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Miami', country: 'USA', timezone: 'America/New_York' },
  { city: 'Milwaukee', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Minneapolis', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Nashville', country: 'USA', timezone: 'America/Chicago' },
  { city: 'New Orleans', country: 'USA', timezone: 'America/Chicago' },
  { city: 'New York', country: 'USA', timezone: 'America/New_York' },
  { city: 'Oklahoma City', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Orlando', country: 'USA', timezone: 'America/New_York' },
  { city: 'Philadelphia', country: 'USA', timezone: 'America/New_York' },
  { city: 'Phoenix', country: 'USA', timezone: 'America/Phoenix' },
  { city: 'Pittsburgh', country: 'USA', timezone: 'America/New_York' },
  { city: 'Portland', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'Raleigh', country: 'USA', timezone: 'America/New_York' },
  { city: 'Sacramento', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'Salt Lake City', country: 'USA', timezone: 'America/Denver' },
  { city: 'San Antonio', country: 'USA', timezone: 'America/Chicago' },
  { city: 'San Diego', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'San Francisco', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'San Jose', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'Seattle', country: 'USA', timezone: 'America/Los_Angeles' },
  { city: 'St. Louis', country: 'USA', timezone: 'America/Chicago' },
  { city: 'Tampa', country: 'USA', timezone: 'America/New_York' },
  { city: 'Washington D.C.', country: 'USA', timezone: 'America/New_York' },
  { city: 'Calgary', country: 'Canada', timezone: 'America/Edmonton' },
  { city: 'Edmonton', country: 'Canada', timezone: 'America/Edmonton' },
  { city: 'Halifax', country: 'Canada', timezone: 'America/Halifax' },
  { city: 'Montreal', country: 'Canada', timezone: 'America/Toronto' },
  { city: 'Ottawa', country: 'Canada', timezone: 'America/Toronto' },
  { city: 'Quebec City', country: 'Canada', timezone: 'America/Toronto' },
  { city: 'Toronto', country: 'Canada', timezone: 'America/Toronto' },
  { city: 'Vancouver', country: 'Canada', timezone: 'America/Vancouver' },
  { city: 'Winnipeg', country: 'Canada', timezone: 'America/Winnipeg' },
  { city: 'Mexico City', country: 'Mexico', timezone: 'America/Mexico_City' },
  { city: 'Guadalajara', country: 'Mexico', timezone: 'America/Mexico_City' },
  { city: 'Monterrey', country: 'Mexico', timezone: 'America/Monterrey' },
  { city: 'Cancún', country: 'Mexico', timezone: 'America/Cancun' },
  { city: 'Tijuana', country: 'Mexico', timezone: 'America/Tijuana' },
  { city: 'Havana', country: 'Cuba', timezone: 'America/Havana' },
  { city: 'Kingston', country: 'Jamaica', timezone: 'America/Jamaica' },
  { city: 'Panama City', country: 'Panama', timezone: 'America/Panama' },
  { city: 'San Juan', country: 'Puerto Rico', timezone: 'America/Puerto_Rico' },
  { city: 'Santo Domingo', country: 'Dominican Republic', timezone: 'America/Santo_Domingo' },
  { city: 'Guatemala City', country: 'Guatemala', timezone: 'America/Guatemala' },
  { city: 'San José', country: 'Costa Rica', timezone: 'America/Costa_Rica' },

  // ── South America ───────────────────────────────────
  { city: 'Bogotá', country: 'Colombia', timezone: 'America/Bogota' },
  { city: 'Medellín', country: 'Colombia', timezone: 'America/Bogota' },
  { city: 'Cali', country: 'Colombia', timezone: 'America/Bogota' },
  { city: 'Buenos Aires', country: 'Argentina', timezone: 'America/Argentina/Buenos_Aires' },
  { city: 'Córdoba', country: 'Argentina', timezone: 'America/Argentina/Cordoba' },
  { city: 'Caracas', country: 'Venezuela', timezone: 'America/Caracas' },
  { city: 'Lima', country: 'Peru', timezone: 'America/Lima' },
  { city: 'Cusco', country: 'Peru', timezone: 'America/Lima' },
  { city: 'Quito', country: 'Ecuador', timezone: 'America/Guayaquil' },
  { city: 'Guayaquil', country: 'Ecuador', timezone: 'America/Guayaquil' },
  { city: 'Santiago', country: 'Chile', timezone: 'America/Santiago' },
  { city: 'Valparaíso', country: 'Chile', timezone: 'America/Santiago' },
  { city: 'São Paulo', country: 'Brazil', timezone: 'America/Sao_Paulo' },
  { city: 'Rio de Janeiro', country: 'Brazil', timezone: 'America/Sao_Paulo' },
  { city: 'Brasília', country: 'Brazil', timezone: 'America/Sao_Paulo' },
  { city: 'Salvador', country: 'Brazil', timezone: 'America/Bahia' },
  { city: 'Fortaleza', country: 'Brazil', timezone: 'America/Fortaleza' },
  { city: 'Recife', country: 'Brazil', timezone: 'America/Recife' },
  { city: 'Manaus', country: 'Brazil', timezone: 'America/Manaus' },
  { city: 'Curitiba', country: 'Brazil', timezone: 'America/Sao_Paulo' },
  { city: 'Belo Horizonte', country: 'Brazil', timezone: 'America/Sao_Paulo' },
  { city: 'Montevideo', country: 'Uruguay', timezone: 'America/Montevideo' },
  { city: 'Asunción', country: 'Paraguay', timezone: 'America/Asuncion' },
  { city: 'La Paz', country: 'Bolivia', timezone: 'America/La_Paz' },

  // ── Oceania ─────────────────────────────────────────
  { city: 'Auckland', country: 'New Zealand', timezone: 'Pacific/Auckland' },
  { city: 'Wellington', country: 'New Zealand', timezone: 'Pacific/Auckland' },
  { city: 'Christchurch', country: 'New Zealand', timezone: 'Pacific/Auckland' },
  { city: 'Sydney', country: 'Australia', timezone: 'Australia/Sydney' },
  { city: 'Melbourne', country: 'Australia', timezone: 'Australia/Melbourne' },
  { city: 'Brisbane', country: 'Australia', timezone: 'Australia/Brisbane' },
  { city: 'Perth', country: 'Australia', timezone: 'Australia/Perth' },
  { city: 'Adelaide', country: 'Australia', timezone: 'Australia/Adelaide' },
  { city: 'Gold Coast', country: 'Australia', timezone: 'Australia/Brisbane' },
  { city: 'Canberra', country: 'Australia', timezone: 'Australia/Sydney' },
  { city: 'Hobart', country: 'Australia', timezone: 'Australia/Hobart' },
  { city: 'Darwin', country: 'Australia', timezone: 'Australia/Darwin' },
  { city: 'Fiji', country: 'Fiji', timezone: 'Pacific/Fiji' },
  { city: 'Suva', country: 'Fiji', timezone: 'Pacific/Fiji' },
  { city: 'Guam', country: 'Guam', timezone: 'Pacific/Guam' },
  { city: 'Noumea', country: 'New Caledonia', timezone: 'Pacific/Noumea' },
  { city: 'Papeete', country: 'French Polynesia', timezone: 'Pacific/Tahiti' },
]
